Art: ['искусство', 'свет', 'огонь', 'творить', 'вдохновение', 'мечтать', 'красивый']
Battle: ['битва', 'кровь', 'безумствовать', 'храбрый', 'герой', 'зло', 'враг']
Love: ['страсть', 'влечение', 'красота', 'сердце', 'целовать']
Epic: ['мощь', 'великий', 'просветление', 'мудрость']
Fear: ['страшно', 'опасность', 'сбежать', 'ужас']
Dark: ['тьма', 'смерть', 'труп', 'отчаяться', 'безумие', 'больно']